### ISSUE TITLE
Change port when using docker-compose

### ISSUE THREAD

**Issue by gerardsyd** [coleifer/sqlite-web#104]
Hi - I am trying to change the default port from 8080 to 12000 using docker-compose but I get the following error:

```
ERROR: for a1a9b5637a2b_sqlite-web  Cannot start service sqlite-web: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "-p": executable file not found in $PATH: unknown

ERROR: for sqlite-web  Cannot start service sqlite-web: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "-p": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```

my docker-compose looks like this:

```
  sqlite-web:
    image: coleifer/sqlite-web:latest
    container_name: sqlite-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - SQLITE_DATABASE="home-assistant_v2.db"
    volumes:
      - ${USERDIR}/docker/homeassistant:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "12000:12000"
    restart: unless-stopped
    command: -p 12000
```

The issue seems to be with the command attribute but not sure why. Any ideas would be great!

**Comment by coleifer** [comment]
You're trying to execute a program named "-p" and docker is saying it can't find it. You need to execute sqlite-web.

**Comment by gerardsyd** [comment]
Thanks for the quick response!

I thought command appended whatever we passed when calling the program through the command line. For example, in my watchtower container, I have:
```
command: --schedule "0 0 4 * * SAT" --cleanup
```


I tried adding sqlite-web to the command in docker-compose and it still doesn't work, see below:

```
ERROR: for a1a9b5637a2b_sqlite-web  Cannot start service sqlite-web: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "sqlite-web": executable file not found in $PATH: unknown

ERROR: for sqlite-web  Cannot start service sqlite-web: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "sqlite-web": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```

Changes made to docker-compose:
```
command: sqlite-web -p 12000
```

**Comment by coleifer** [comment]
I don't really use docker compose so I have no idea.

**Comment by gerardsyd** [comment]
Hi - I updated the dockerfile to have the port as a variable and this now works. This is what my dockerfile looks like now:
```
FROM coleifer/sqlite
RUN apk add --no-cache --virtual .build-reqs build-base gcc make \
      && pip install --no-cache-dir cython \
      && pip install --no-cache-dir flask peewee sqlite-web \
      && apk del .build-reqs
EXPOSE $SQLITE_PORT
VOLUME /data
WORKDIR /data
CMD sqlite_web -H 0.0.0.0 -x $SQLITE_DATABASE -p $SQLITE_PORT
```

and my docker-compose now just has the SQLITE_PORT as a variable. not sure if there's a way to set it to 8080 as default but this works for my use case

**Comment by coleifer** [comment]
Thank you so much for the update, hopefully it helps the next person who runs into this

**Comment by ptath** [comment]
@gerardsyd 

>  but this works for my use case

can you please paste your actual docker-compose.yml here?

**Comment by gerardsyd** [comment]
Sure, see below. I'm not using this any more so not sure if it still works. 

```
# SQLite Web
    sqlite-web:
      image: coleifer/sqlite-web:latest
      container_name: sqlite-web
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=$TZ
        - SQLITE_DATABASE=[redacted]
        - SQLITE_PORT=12000
      volumes:
        - ${DOCKERDIR}/[datafolder]:/data
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.http.routers.sqlite-web-rtr.entrypoints=https"
        - "traefik.http.routers.sqlite-web-rtr.rule=Host(`sqlite-web.$DOMAINNAME`)"
        - "traefik.http.routers.sqlite-web-rtr.tls=true"
        ## Middlewares
        - "traefik.http.routers.sqlite-web-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
        ## HTTP Services
        - "traefik.http.routers.sqlite-web-rtr.service=sqlite-web-svc"
        - "traefik.http.services.sqlite-web-svc.loadbalancer.server.port=12000"
      ports:
        - "12000:12000"
      restart: unless-stopped
      networks:
        - t2_proxy
      security_opt:
        - no-new-privileges:true
      command: "-P 12000"
```
