### ISSUE TITLE
How to specify SQLITE_WEB_PASSWORD in k8s deploy?

### ISSUE THREAD

**Issue by victory460** [coleifer/sqlite-web#136]
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rj-cni-sqlite
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: rj-cni-sqlite
  template:
    metadata:
      labels:
        app: rj-cni-sqlite
    spec:
            #nodeSelector:
            #topology.kubernetes.io/zone: suzhou
      containers:
      - name: rj-cni-sqlite
        image: sdn.harbor.io:28181/bcgtm/cni/rj-cni-sqlite:v1.0
        imagePullPolicy: Always
        # command: ["sh","-c","sqlite_web -H 0.0.0.0 -p 18011 -x /data/log/rj-cni/cni.db"]
        command:
          - /bin/sh
          - -ce
          - export SQLITE_WEB_PASSWORD="web2lite";sqlite_web -H 0.0.0.0 -p 18012 -x /data/log/rj-cni/cni.db
        ports:
        - containerPort: 18012
          hostPort: 18012
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data/log/rj-cni
          name: logdir
        env:
          - name: SQLITE_WEB_PASSWORD
            value: "web2lite"
      hostNetwork: true
      volumes:
      - hostPath:
          path: /data/log/rj-cni
          type: DirectoryOrCreate
        name: logdir
```
