### ISSUE TITLE
Docker - cant start Container - exec /bin/sh: exec format error

### ISSUE THREAD

**Issue by justinh998** [coleifer/sqlite-web#172]
Hello, I generated a Docker image using the Docker file from the repository
`docker build --platform linux/arm64 -t coleifer/sqlite-web`
and started it with this docker-compose (this is just a snippet, my compose file includes multiple services):
```
  sqlite-web:
    container_name: sqlite-web_ruth
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - /home/justin/sqliteweb:/data
    environment:
      - SQLITE_DATABASE=home-assistant_v2.db
    restart: unless-stopped 
```
However, I only get the error in the container log: exec /bin/sh: exec format error

The container does not create any files and is not accessible on port 8080. Has anyone encountered the same error and can help me?
