### ISSUE TITLE
One possible improvement

### ISSUE THREAD

**Issue by yumusb** [coleifer/sqlite-web#173]
https://github.com/coleifer/sqlite-web/blob/928fc630ca71aa12b4e4bc26a8a0b4d97f628df8/sqlite_web/sqlite_web.py#L1386-L1388

Currently, it's necessary to specify --password and set a password in the command line to enable password protection. However, in a Docker Compose setup, the configuration looks like this:
``` yml
sqlite-web:
  image: ghcr.io/coleifer/sqlite-web:latest
  restart: always
  volumes:
    - ./somedata.db:/app/somedata.db
  environment:
    - SQLITE_WEB_PASSWORD=xxxxx
  command: sqlite_web -H 0.0.0.0 -x /app/somedata.db --password
```
This requires using both an environment variable and a command-line parameter.

It would be more convenient if an environment variable could be added to indicate whether to enable password protection. For example, something like this would eliminate the need to override the command parameter:
``` yml
sqlite-web:
  image: ghcr.io/coleifer/sqlite-web:latest
  restart: always
  volumes:
    - ./somedata.db:/app/somedata.db
  environment:
    - SQLITE_WEB_PASSWORD=xxxxx
    - SQLITE_WEB_PASSWORD_ENABLE=true
```

If you think this is feasible, I can provide a PR.
